### ISSUE TITLE
deployment to Amazon S3 is not automated

### ISSUE THREAD

**Issue by yegor256** [egis/parent#17]
At the moment there is no possibility to publish a new version of this module to Amazon S3. I assume that this operation is automated somehow, but we don't have any explicit instructions in README. Let's fix it.

I think the cap here is 3 hours.

**Comment by yegor256** [comment]
@Egis-Moshe what do you think? Let's do it? I would use Rultor for that, just like we're using it for merging already.

**Comment by Egis-Moshe** [comment]
@yegor256 we currently have this working using circleci on successful build of master

```
deployment:
  production:
    branch: master
    commands:
      - gradle-2.7/bin/gradle publish
```
